<a href="https://colab.research.google.com/github/nishant26baisoya-code/Data-science_gen_-ai_project/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy:

#Numpy ---->stands for Numerical Python
#NumPy is to perform mathematical and statistical operations.
#It has been built to work with the N-dimensional array, linear algebra,
#random number etc.

import numpy as np

# !pip install numpy

#to know the numpy version

print(np.__version__)

#ex1: Creating a Numpy Array from a list

list1=[1,2,3,4,5]
print(list1)

array1=np.array(list1)
print(array1,type(array1))

#or
x=np.array([10,20,30,40])

print(x)

print("\n")

#Note :Numpy arrays are faster as compared with Lists especially when working
#     witj large datasets

#ex:2 performing mathematical operations like additions,subtraction,division and multiplication on an array
y=array1+10
print(y)

z=y-1
print(z)

w=z*2
print(w)


#3) shape of the array and dtype
print(array1.shape)    #returns no of elements
print(array1.dtype)

#4)float type
array2=np.array([1.5,2.5,3.5,4.5])
print(array2)
print(array2.shape)
print(array2.dtype)

#5)2 dimensional array
c = np.array([(1,2,3),
              (4,5,6)])
print(c)
print(c.shape)   #2-rows and 3 cols
print(c.dtype)


#6) 3 dimensional array
d = np.array([
    [[1, 2,3],
     [4, 5, 6]],

    [[7, 8,9],
    [10, 11, 12]]
        ])
print(d)
print(d.shape)  #(2,2,3) i.e 2  2x3 arrays



#7)np.zeros
#  np.ones
#we can create a matrix full of zeroes or ones using np.zeros and np.one commands.
#It can be used when you initialized the weights during the first iteration in
#TensorFlow and other statistic tasks.
# syntax :np.zeros(shape, dtype=float)
print(np.zeros((2,2)))


print(np.zeros((2,2), dtype=np.int16))

print(np.ones((1,2,3), dtype=np.int16))  #one 2-D array


#8)reshape():in some occasions, you need to reshape the data from wide to long
#syntax:  np.reshape(a, newShape)
#a: Array that you want to reshape

#newShape: The new desired shape

e  = np.array([(1,2,3), (4,5,6)])  #2x3
print(e)
print(e.reshape(3,2))        #3x2
#print(e.reshape(5,2))
print(e.reshape(6,1))

#examples of reshape:
#1.python databases
#2.Machine Learning Analytics

#9)flatten():flattening the array,When you deal with some neural network like,we need to
#flatten the array
print(e)
print(e.flatten())


#10)# Horitzontal Stack: appending data horizontally
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

#11)# Vertical Stack :Appending data vertically
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))



2.0.2
[1, 2, 3, 4, 5]
[1 2 3 4 5] <class 'numpy.ndarray'>
[10 20 30 40]


[11 12 13 14 15]
[10 11 12 13 14]
[20 22 24 26 28]
(5,)
int64
[1.5 2.5 3.5 4.5]
(4,)
float64
[[1 2 3]
 [4 5 6]]
(2, 3)
int64
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]]
[[[1 1 1]
  [1 1 1]]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np
#Numpy - Array From numerical Ranges

#14) Arrange() :generating range of values
#syntax: numpy.arrange (start, stop,step)
#Start: start of interval
#Stop End of Interval
#Step: Spacing between values. Default step is 1
print(np.arange(11))
# dtype set
x = np.arange (5,dtype = float)
print(x)
print (np.arange(1,20,2))

[ 0  1  2  3  4  5  6  7  8  9 10]
[0. 1. 2. 3. 4.]
[ 1  3  5  7  9 11 13 15 17 19]


In [3]:
#15)numpy.linspace
#This is function is similar to arrange() function.
#here instead of step size, the number of evenly spaced values between the interval is specified.
#syntax:
#numpy.linspace (start,stop, num)

#here the 3rd parameter num---->is the number of evenly spaced samples to be generated.
#Default is 50

x=np.linspace(10,20,5)
print(x)

'''
o/p
[10. 12.5  15.   17.5  20.]'''

#ex2)
x = np.linspace(10,20,6)
print(x)

"""
o/p
[10  12  14  16  18  20]"""

[10.  12.5 15.  17.5 20. ]
[10. 12. 14. 16. 18. 20.]


'\no/p\n[10  12  14  16  18  20]'

In [4]:
#16)NumPy - Indexing & Slicing
import numpy as np
a = np.arange(20)
s = slice(2,10,2)
print(a[s])


#or
a = np.arange(20)
b = a[2:10:2]
print(b)

x=[0,1,2,3,4,5,6,7,8,9]
x[0]=0
x[1]=1
x[4]=4
x[5]=5
#ii) #accessing a particular value
a = np.arange(10)
b = a[5]
print(b)

#iii)
a = np.arange(10)
print(a[2:])

#iv)
a = np.arange(10)
print(a[2:5])

#V) slicing on multi-dimensional ndarray
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

#Vi) slice items starting from index
print('Now we will slice the array from the index a[1:]' )
print(a[1:])

[2 4 6 8]
[2 4 6 8]
5
[2 3 4 5 6 7 8 9]
[2 3 4]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [5]:
#vii)Slicing can also include ellipse(...)
a = np.array ([[1,2,3],
              [3,4,5],
              [4,5,6]])
print('our array is:')
print(a)
print('\n')

#this return array of items in the second column
print('this items in the second column are:')
print(a[...,1])
print('\n')

#Now we will slice all items from the second row
print('The items in the second row are:')
print(a[1,...,])
print('\n')

#Now we will slice all items from column 1 onwards
print('The items column 1 onwards are:')
print(a[...,1:])

print(a[1:,...])
print(a[1:,1:])

our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


this items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]
[[3 4 5]
 [4 5 6]]
[[4 5]
 [5 6]]


In [6]:
#17)NumPy - Iterating Over Array

#NumPy package contains an iterator object numpy.nditer. It is an efficient
#multidimensional iterator object using which it is possible to iterate over
#an array.creating a 3X4 array using arange() function and iterate over it using nditer.

import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

print(a)
print("\n")

for p in np.nditer(a):
   print(p)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


0
5
10
15
20
25
30
35
40
45
50
55


In [7]:
#18) Transpose : here rows becomes columns

a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a)
print('\n')

print('Transpose of the array is:' )
b = a.T
print(b)
print('\n')

for i in np.nditer(b):
   print(i)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


0
5
10
15
20
25
30
35
40
45
50
55


In [8]:
#20.Array Manipulation
#i)split: Split an array into multiple sub-arrays
import numpy as np
a = np.arange(9)
print(a)
print('\n')

print ('Split the arrays at position indicated in 1-D array')
b = np.split(a,[4,7])
print(b)
#ii)hspit(): Split an array into multiple sub=arrays horizontally (column-wise)

a = np.arange(16).reshape(4,4)

print(a)

print('Horizontal Splitting:')
b= np.hsplit(a,2)
print(b)
print('\n')


[0 1 2 3 4 5 6 7 8]


Split the arrays at position indicated in 1-D array
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Horizontal Splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]




In [9]:
#Finding dimension of a array

#ndim: This can be used to find the dimension of the array.

import numpy as np
arr = np.array([[1,2,3,4],[4,5,6,7],[9,10,11,23]])
print(arr.ndim)
print(arr)

#------------------------------------------------------------------------------
#sum(),max(),min()
a = np.array([1,2,3,10,15,4])
print("The array:",a)
print("The maximum element:",a.max())
print("The minimum element:",a.min())
print("The sum of the elements:",a.sum())




2
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 9 10 11 23]]
The array: [ 1  2  3 10 15  4]
The maximum element: 15
The minimum element: 1
The sum of the elements: 35


In [10]:
#arithmetic operations are performed on the two multi-dimensional arrays a and b.
import numpy as np
a = np.array([[1,2,30],[10,15,4]])
b = np.array([[1,2,3],[12, 19, 29]])
print("Sum of array a and b\n",a+b)
print("Product of array a and b\n",a*b)
print("Division of array a and b\n",a/b)

Sum of array a and b
 [[ 2  4 33]
 [22 34 33]]
Product of array a and b
 [[  1   4  90]
 [120 285 116]]
Division of array a and b
 [[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  0.13793103]]


In [11]:
#NumPy Functions

#1)numpy.sum(): This function is used to compute the sum of all elements,
#the sum of each row and the sum of each column of a given array.

import numpy as np
a=np.array([0.5,0.3])
b=np.sum(a)
print(b)


import numpy as np
a=np.array([0.4,0.5,0.9,6.1])
x=np.sum(a, dtype=np.int32)
print(x)
#o/p :6
#Note:in the output, the sum only of integer numbers, not floating-point values has been displayed.

#ex:3
import numpy as np
a=np.array([[1,4],[3,5]])
b=np.sum(a)
print(b)
#o/p :13

#ex:4 column sum

import numpy as np
a=np.array([[1,4],
            [3,5]])
b=np.sum(a,axis=0)
print(b)
#o/p:([4, 9])


#ex:5  row sum
import numpy as np
a=np.array([[1,4],
            [3,5]])
b=np.sum(a,axis=1)
print(b)
#o/p:array([5, 8])


0.8
6
13
[4 9]
[5 8]


In [12]:

import numpy as np
#numpy.append():The numpy.append() function is used to add or append new values to an
#               existing numpy array.
#The numpy append() function is used to merge two arrays. It returns a
#new array,and the original array remains unchanged.

a=np.array([[1, 2, 3],[4, 5, 6]])
b=np.array([[7, 8, 9],[10,11,12]])
c=np.append(a,b)
print(c)


#ex:2
import numpy as np
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])
c=np.append(a,b,axis=0)
print(c)
#o/p:
'''
array([[ 10,  20,  30],
       	[40, 50, 60],
       	[70, 80,90],
      	[11, 21,31],
       	[42, 52,62],
       	[73, 83,93]],)
'''

#ex:3
import numpy as np
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])
c=np.append(a,b,axis=1)
print(c)
#o/p:
'''
array([[ 10,  20,  30, 11, 21, 31],
       	[ 40,  50,  60, 42, 52, 62],
       	[ 70,  80,  90, 73, 83, 93]])
'''



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [11 21 31]
 [42 52 62]
 [73 83 93]]
[[10 20 30 11 21 31]
 [40 50 60 42 52 62]
 [70 80 90 73 83 93]]


'\narray([[ 10,  20,  30, 11, 21, 31],\n       \t[ 40,  50,  60, 42, 52, 62],\n       \t[ 70,  80,  90, 73, 83, 93]])\n'

In [21]:
#numpy. where() for selecting element based on a condition.

import numpy as np
a=np.arange(12)
b=np.where(a<6,a,5*a)
print(b)

#o/p
#array ([0, 1, 2, 3, 4, 5, 30, 35, 40, 45, 50 55])
#Note the value ranging from 0 to 5 remain the same as per the condition,
#and the tower the values have been multiplied with 5.



[ 0  1  2  3  4  5 30 35 40 45 50 55]


In [15]:
#Numpy Linear Algebra

#Numpy package contains numpy.linalg module that provide all the functionality required
#for linear algebra
#Some of the important function with in this module are described in the following table.

#1)Dot: Dot product of the two arrays

import numpy.matlib
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(a)
print(b)
print(np.dot(a,b))
'''
[1 2] [11 12]
[3 4] [13 14] '''
'''
o/p:
[[37 40]
 [85 92]]

'''
'''
the dot product is calculated as -
[[1*11*13, 1*12+2*14],[3*12+4*14]] '''

print("\n\n")
#----------------------------------------------------------------------------------------------------

#2)vdot :Dot product of the two vectors
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(np.vdot(a,b))

#o/p : 130
'''
[1 2] [11 12]
[3 4] [13 14] '''

#1*11 + 2*12 + 3*13 + 4*14 = 130
print("n\n")
#---------------------------------------------------------------------------------------------------
#3)inner : Inner product of the two arrays

import numpy as np
print(np.inner(np.array([1,2,3]),np.array([0,1,0])) )

#o/p: 2
# Equates to 1*0+2*1+3*0

print("\n\n")
#ex:2
#Multi-dimensional array example

import numpy as np
print(np.inner(np.array ([1,2,3]),np.array([0,1,0])) )

#o/p: 2
# Equates to 1*0+2*1+3*0

print("\n\n")
#ex: 2

#Multi-dimensional array example

import numpy as np
a = np.array ([[1,2], [3,4]])

print('Array a:')
print(a)
b = np.array ([[11, 12], [13, 14]])

print('Array b:')
print(b)

print('Inner Product:')
print(np.inner(a,b))

'''
o/p:

[[35 41]
 [81 95]] '''

'''
[1 2] [11 12]
[3 4] [13 14] '''


''' Inner product calculated as
1*11+2*12, 1*13+2*14
3*11+4*12, 3*13+4*14 '''

#-------------------------------------------------------------------------------------------------


[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[37 40]
 [85 92]]



130
n

2



2



Array a:
[[1 2]
 [3 4]]
Array b:
[[11 12]
 [13 14]]
Inner Product:
[[35 41]
 [81 95]]


' Inner product calculated as\n1*11+2*12, 1*13+2*14\n3*11+4*12, 3*13+4*14 '

In [22]:

#Numpy String Functions:
#1.add():This function performs element wise string concatenation.

import numpy as np
print('Concatenate two strings:')
print(np.char.add(['hello'],[' world']))
print('\n')

print('Concatenation example:')
print(np.char.add(['hello', 'hi'],[' Amar', ' JAmes']))

print("\n\n")

#--------------------------------------------------------------------------------------------
#2.multiply()

import numpy as np
print(np.char.multiply('Hello ',3))

print("\n\n")

#--------------------------------------------------------------------------------------------
#3.capitalize():This function returns the copy of the string with the first letter capitalized.
import numpy as np
print(np.char.capitalize('hello world'))

#--------------------------------------------------------------------------------------------
#4.title(): the first letter of each word capitalized.

import numpy as np
print(np.char.title('hello how are you?'))

#-------------------------------------------------------------------------------------------------
#5.replace():

import numpy as np
print(np.char.replace ('Sachin is a good Player', 'Sachin', 'Kohli'))

#-------------------------------------------------------------------------------------------------
#6.upper():

import numpy as np
print(np.char.upper('hello'))
print(np.char.upper(['hello','world']))


Concatenate two strings:
['hello world']


Concatenation example:
['hello Amar' 'hi JAmes']



Hello Hello Hello 



Hello world
Hello How Are You?
Kohli is a good Player
HELLO
['HELLO' 'WORLD']
