<a href="https://colab.research.google.com/github/nishant26baisoya-code/Data-science_gen_-ai_project/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Datatypes

In [ ]:
#String :Sequence Collection of characters
# In python, a string is represented using
# 1.Single quote(' ')
# 2.Double quote(" ")
# 3.Triple quote(''' ''')


# String supports 2 types of indexes:
# #1.positive index or forward index starts from left to right ---->starts with 0
# #2.Negative index or backward index--->starts from right to left--->starts with -1
#    0123456789------->positive index # This line caused a SyntaxError
x="Data Science"
# #               -1---->Negative index # This line also caused a SyntaxError

print(x[0])
print(x[2])

print(x[-1]) # Corrected index from [-1] to x[-1]
print(x[-3])



#String methods:
# 1.upper(): To print in uppercase
x="Data science"
print(x.upper())
# 2.lower(): To print lower case
x="ARTIFICIAL INTELLIGENCE"
print(x.lower())

#3.Capitalize() :for Capitalizing the 1st character
x="india"
print(x.capitalize())

#4.title() :For caitalizing the 1st character of each word in a string
x="mahendra singh dhoni"
print(x.title())

#ex:2
emps="rahul,ajay,miller,blake,james,john,amar,rajesh"
print(emps.title())

#5.replace() :for replacing of a string
X="Rohit is the captain of India"
print(X.replace("Rohit","Gill"))

#6.count() :To count the no of occurences of or a character
medals="Ind,Jap,Eng,Aus,Ind,Eng,Jap,Ind,Aus,Eng"
print(medals.count("Ind"))
print(medals.count("A"))
#==============================================================================
#7.format():for substitution
X="{} is the trending Technolgy currently"
print(X.format("Data Science"))
#ex:
y="{} is the {} of {}"
print(y.format("Delhi","capital","India"))
print(y.format("python","most popular","all languages"))

import datetime
p=str(datetime.datetime.now())

z="Todays date is {}"
print(z.format(p))
#==============================================================================
#8.find() :To check whether a sub-string is available or not
#If available it returns the 1st characters index position of sub-string
#else it returns -1

x="Python is easier than Java"
print(x.find("Java"))
print(x.find("python"))
print(x.find("spark"))

#================================================================================
#9 split() :If we split a string,we get a list

x="welcome to Datascience"
#print-->only Datascience from the above
y=x.split(" ")
print(y,type(y))
print(y[2])

#ex:2
emp="101,Ajay,90000,Manager"
#print--->Name and designation
y=emp.split(",") # Corrected from x.emp.split(",") to emp.split(",")
print(y,type(y))
print(y[1],y[3])

D
t
e
n
DATA SCIENCE
artificial intelligence
India
Mahendra Singh Dhoni
Rahul,Ajay,Miller,Blake,James,John,Amar,Rajesh
Gill is the captain of India
3
2
Data Science is the trending Technolgy currently
Delhi is the capital of India
python is the most popular of all languages
Todays date is 2025-09-25 10:52:48.766562
22
-1
-1
['welcome', 'to', 'Datascience'] <class 'list'>
Datascience
['101', 'Ajay', '90000', 'Manager'] <class 'list'>
Ajay Manager


# IF -else

In [ ]:
#syntax for If else:
if(conditions):
  stm1
  stm2 ------>Block1
  stm3
  stm4
else:
  stm5
  stm6 ------>Block2
  stm7
  stm8
If the condition is True then the stmts within the if-block1(block1) executes
if the Condition is False then the stmts within the else block executes


In [ ]:
#Check whether a given number is positive or negative
x=-5
if(x>0):
  print(x,"is a positive number")
else:
  print(x,"is a nagative number")

-5 is a nagative number


In [ ]:
#Check whhther a given number is even or odd
x=28
if(x%2==0):
  print(x,"is a even number")
else:
  print(x,"is a odd number")

28 is a even number


In [ ]:
#elif : For providing multiple condition
time=21.22
if(time<=12.00):
  print("Good Morning!!!")
elif(time<=16.00):
  print("Good Afternoon!!")
elif(time<=20.00):
   print("Good Evening!!!")
else:
  print("Good Night!!!")


Good Night!!!


## for loop

In [ ]:
#For loop :For loop executes set of stmts for every element of collection object

x=[10,20,30,40,50]
for p in x:
  print(p)

10
20
30
40
50


In [ ]:
#ex:2
#printing a msg for multiple times
x=[10,20,30,40,50]
for p in x:
  print("Good Evening!!!")

Good Evening!!!
Good Evening!!!
Good Evening!!!
Good Evening!!!
Good Evening!!!


In [ ]:
#range(n) : generates range of values from 0 to n-1
#ex: range(10)--->generates values from 0 to 9

x=range(10)
print(x)

#retrieving one by one value using for loop
for p in x:
  print(p)
#ex:2
y=range(10,20)
for p in y:
  print(p)

#ex:3
z=range(20,30,2)
for p in z:
  print(p)

#Ex:4
w=range(40,30,-1)
for p in w:
  print(p)

#printing nos from 1 to 100
for p in range(1,101):
  print(p,end=" ")
print("\n")
#printing even nos upto 200
for p in range(2,201,2):
  print(p,end=" ")

range(0, 10)
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
22
24
26
28
40
39
38
37
36
35
34
33
32
31
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 

2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180 182 184 186 188 190 192 194 196 198 200 

# while loop


In [ ]:
#while loop :for executing set of stmts for repeated number of times or for multiple times

#syntax:

initialization
while(condition):
  stmts1
  stmts2
  stmts3
  increment/decrement



In [ ]:
#ptinting nos from 1 to 10
x=1
while(x<=10):
  print(x)
  x=x+1
print("end")


1
2
3
4
5
6
7
8
9
10
end


In [ ]:
#printing a msg for 10 times
x=1
while(x<=10):
  print("Hello")
  x=x+1
print()

# collections in python

In [ ]:
#1. List : holding group of values

#List properties

#1)-List represented using []

#2) allows both homogenous(similar) and haterogenous(dissimilar)
   x=[10,20,30,40,50] --->homogenous
   y=[101,"Ajay",80970.40]--->heterogenous

#3)List allows duplicates ----->x=[10,20,30,40,50,10,20,30,]

#4)List is ordered ----> how the elements are inserted in same order they are stored

#5)List is mutable object--->Changes of modification are allowed

#6)List supports indexing
      0   1   2  3 4
   x=[10,20,30,40,50]

In [ ]:
x=[10,20,30,40,50]
print(x)
x[2]=35
print(x)

#printing particulr element from a list using index
print(x[0])
print(x[1])

#printing 1st 3 element
#printing(x[0:3]) #upper bound is excluded

[10, 20, 30, 40, 50]
[10, 20, 35, 40, 50]
10
20


In [ ]:
#List function
x=[30,40,10,20,50]
print(x)
print(len(x))
print(max(x))
print(min(x))
print(sum(x))
avg=sum(x)/len(x)
print(avg)
print(sorted(x)) #proints in ascending order
print(sorted(x,reverse=True))

[30, 40, 10, 20, 50]
5
50
10
150
30.0
[10, 20, 30, 40, 50]
[50, 40, 30, 20, 10]


In [ ]:
#List methods

x=[10,20,30,40,50,]
#1.append() :For appending an element the end of list
x.append(60)
print(x)

#2.extend() :For extending a list with the elements of other list
y=[15,25,35,45,55]
x.extend(y)
print(x)

#3.insert(index,value) :For inserting at the desired position
x.insert(2,25)
print(x)
#4.pop(index) :removing element based on index
x.pop(3)
print(x)

#5.remove() :removing element based on value
x.remove(40)
print(x)

#6.sort() :for sorting elements of a list
x=[5,3,4,1,2]
x.sort()
print(x)

#7.reverse() :for reversing a list
x.reverse()
print(x)

#8.count: To count the no of occurences of a element in the list
medals=["India","Aus","Eng","Ind","Aus","Eng","Ind","Jap","Ind"]
print(medals.count("Ind"))

[10, 20, 30, 40, 50, 60]
[10, 20, 30, 40, 50, 60, 15, 25, 35, 45, 55]
[10, 20, 25, 30, 40, 50, 60, 15, 25, 35, 45, 55]
[10, 20, 25, 40, 50, 60, 15, 25, 35, 45, 55]
[10, 20, 25, 50, 60, 15, 25, 35, 45, 55]
[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]
3


# Tuples

In [ ]:
#Tuples :Tuples are immutable
#        Here We cannot insert ,modify,delete
#        Once tuple is defined it is constant

In [ ]:
#1. Tuple : holding group of values
#Tuple properties

#1)-List represented using ()

#2) allows both homogenous(similar) and hetarogenous(dissimilar)
   x=(10,20,30,40,50) ------> homogenous
   y=(101,"Ajay",80970.40)--->heterogenous

#3)Tupple allows deplicates ----->x=(10,20,30,40,50,10,20,30)

#4)Tuple is ordered ---->how the element are inserted in same order they are stored

#5)Tuple is a immutable object--->Changes and modification are not allowed

#6) Tuple supports indexing
       0   1  2  3 4
    x=[10,20,30,40,50]

In [ ]:
x=(10,20,30,40,50)

print(x[0])
print(x[-1])
print(x[-3])
print(x,type(x))

x=10,20,30
print(x,type(x))

emps="Ajay","Rohith","Miller"
print(emps,type(emps))

x=(10) #if one element in tuple, it is not a tuple whetever element present
       #it takes that type
print(x,type(x))

x=(10,)
print(x, type(x))

x=("Rahul")
print(x,type(x),len(x))

x=10
print(x,type(x))

x=10,
print(x,type(x))

x=([10,20,30])
print(x,type(x),len(x))

x=[10]
print(x,type(x))

x=[(10,20,30)]
print(x,type(x))

x=[1,2,3],[4,5,6]
print(x,type(x))

#merging tupes
x=(10,20,30)
y=(40,50,60)
z=x+y
print(z,type(z),len(z))

a="hello"
print(a*3)
z=x*3
print(z)

#Tuple packing: Creating tuple without braces
x=1,2,3
print(x,type(x))

#Tuple unpacking :Assigning tuple to multiple variables
marks=(90,70,80)
maths,phy,chem=marks
print(maths,type(maths))
print(phy,type(phy))
print(chem,type(chem))

emps=("Ajay","Rohith","Amar")
e1,e2,e3=emps
print(e1,type(e1))
print(e2,type(e2))
print(e3,type(e3))

10
50
30
(10, 20, 30, 40, 50) <class 'tuple'>
(10, 20, 30) <class 'tuple'>
('Ajay', 'Rohith', 'Miller') <class 'tuple'>
10 <class 'int'>
(10,) <class 'tuple'>
Rahul <class 'str'> 5
10 <class 'int'>
(10,) <class 'tuple'>
[10, 20, 30] <class 'list'> 3
[10] <class 'list'>
[(10, 20, 30)] <class 'list'>
([1, 2, 3], [4, 5, 6]) <class 'tuple'>
(10, 20, 30, 40, 50, 60) <class 'tuple'> 6
hellohellohello
(10, 20, 30, 10, 20, 30, 10, 20, 30)
(1, 2, 3) <class 'tuple'>
90 <class 'int'>
70 <class 'int'>
80 <class 'int'>
Ajay <class 'str'>
Rohith <class 'str'>
Amar <class 'str'>


In [ ]:
#Tuple function
x=(40,10,30,20,50)
print(x)
print(len(x))
print(max(x))
print(min(x))
print(sum(x))
print(sorted(x)) #we get a list in sorted order
print(sorted(x,reverse=True))

(40, 10, 30, 20, 50)
5
50
10
150
[10, 20, 30, 40, 50]
[50, 40, 30, 20, 10]


# SETS

In [ ]:
#Sets : collection of elements

#Set properties

#1.Sets represented using {}

#2.Sets allows heterogenous elements

#3.Sets doesnt allow duplicates x={10,20,30,10,30}

#4.Sets are un-ordered x={10,20,30,40,50}

#5.Sets doesnt support indexing

#6.Sets are mutable ----> changes and modifications are allowed

#7.sets allows only immutable,sets wont allow mutables, even set not allowed within a set

In [ ]:
x={10,20,30,40,50}
print(x,type(x))

#set methods --> add(),update(),pop(),remove(),clear()
#1.add() :To add an element in to the set
x.add(60)
print(x,len(x))

x.add((55,65,75)) #tuples gets added
print(x,len(x))

#2.update(): for updating multiple elements ata time
x.update((70,80,90)) #here 3 elements gets added
print(x,len(x))

#3.pop() for removing a radomly
x.pop()
print(x)
x.pop()
print(x)

#4.remove() :For removing a particular element
x.remove(40)
print(x)
x.remove((55,65,75))
print(x)

#5.clear() :clears all the set elements
x.clear()
print(x)

#set mathematicals methods
A={10,20,30,40,50,60}
B={10,20,30,70,80,90}

#6.union():union of 2 sets
print(A.union(B))

#7.intersection() : returns common elements of
print(A.intersection(B))

#8.difference():
print(A.difference(B))
print(A-B)
print(B.difference(A))
print((B-A))

{50, 20, 40, 10, 30} <class 'set'>
{50, 20, 40, 10, 60, 30} 6
{50, (55, 65, 75), 20, 40, 10, 60, 30} 7
{70, 10, 80, 20, 90, 30, (55, 65, 75), 40, 50, 60} 10
{10, 80, 20, 90, 30, (55, 65, 75), 40, 50, 60}
{80, 20, 90, 30, (55, 65, 75), 40, 50, 60}
{80, 20, 90, 30, (55, 65, 75), 50, 60}
{80, 20, 90, 30, 50, 60}
set()
{70, 40, 10, 80, 50, 20, 90, 60, 30}
{10, 20, 30}
{40, 50, 60}
{40, 50, 60}
{80, 90, 70}
{80, 90, 70}


# Dictionary

In [ ]:
#Dictionary :Dictionary is a collection (key,value) pairs
ex: x={"name","Ajay","age":25,"city":"pune"}
         k      v     k    v    k      v
Dictionary properties:

1.No insertion order
2.No duplicate keys but duplicate value allowed
  ex: x="age":60,"weight":60}

3.No indexing

4.Dictionary is a mutable object--->changes and modication allowed
                                    i.e we can insert, remove and modify
5.If we pass the key we get the value

In [ ]:
x={}
print(type(x))

x={'a':10,'b':20}
print(x,type(x),len(x))

#If we pass the key,we get the value
print(x['a'])
print(x['b'])

#duplicates keys are not allowed
x={'a':10,'b':20,'b':30,'a':40}
print(x,len(x))
print(x['a'])
print(x['b'])

#modifying adding and removing element from a dictionary
x={"name":"Ajay","age":25}
print(x)
#modify the age to 28
x["age"]=28
print(x)
#adding a new key--->city
x["city"]="chennai"
print(x)

#removing the age
x.pop("age")
print(x)

#clearing all the elements
x.clear()
print(x)

<class 'dict'>
{'a': 10, 'b': 20} <class 'dict'> 2
10
20
{'a': 40, 'b': 30} 2
40
30
{'name': 'Ajay', 'age': 25}
{'name': 'Ajay', 'age': 28}
{'name': 'Ajay', 'age': 28, 'city': 'chennai'}
{'name': 'Ajay', 'city': 'chennai'}
{}


# Functions

In [ ]:
#Functions:
-Block of stmts which performs particular task
-Functions are not executed automatically,
-To execute functions, we need to make a function call

-Functions are defined by using a keyword def
-all the stmt within the function should follow the indentation

#syntax:
def functionname(arguments):
  stmt1
  stmt2
  stmt3
  stmt4
  return stmt

#specifying arguments and returntype is optional

In [ ]:
#ex: Function to display a msg
def message():
  print("Hello")
  print("Good Evening!!!!")
message() #calling a function---> tehn only stmts within the function executes
message() #one more time function executes

Hello
Good Evening!!!!
Hello
Good Evening!!!!


In [ ]:
#ex:2 Functions with arguments
def add(x,y): #2 arguments
  z=x+y
  print("z=",z)
add(10,20)

z= 30


In [ ]:
#Function with return type
def add(x,y): #with argument
  z=x+y
  return z    #with return type
p=add(30,40)  #whetever the function return will be stored within the function call
print(p)

#advantage of returntype -->the computed result of a function, if to be used in the
# later partof the program then use return stmt



70


In [ ]:
#Advantage of return stmt
#compute tax(10%)) and also compute netsal

sal=80000
def compute():
    tax=sal*0.10
    return tax

  t=compute() #whetever the function return will be stored by the function call
              #and is assigned to variable t
  netsal=sal-t
  print("NETSAL=",netsal)


In [ ]:
#Lambda Function
#Function without anyname
#If function doesnt have a name, then how to call it
#assign the function to a variable and the variable  behaves the like the function name
#synatax for defining lambda function
#lambda argument :expression
#we can have any no of arguments but only one expression

#Lambda Function to square a number

#Lambda Function to square a number
f=lambda x:x*x
print(f(10))

#ex2
p=lambda x,y:x*y
print(p(20,30))

100
600


In [ ]:
#using lambda as an argument to other function like filter(),map()
#filter () : for filtering based on data
#filter takes 2 arguments
#1.lambda as 1st argument
#2.collection like list tuple

list1=[10,20,30,40,50,60,70]
#Task :filter only those whose value is above 40
res=list(filter(lambda x:x>40,list1))   #here x is element of the list,which is of type int
print(res)

#ex:2
emps=[[101,"ajay",10000,'m',11,'hyd'],
      [102,"rahul",20000,'m',12,'pune'],
      [103,"priya",300000,'f',13,'hyd'],
      [104,"Anitha",40000,'f',14,'hyd'],
      [105,"jame",500000,'m',15,'pune']
     ]
#Task1 : Filter records only "hyd" employee records
hyd_recs=list(filter(lambda x:x[5]=="hyd",emps))
print(hyd_recs)
print("\n")

#Task2 : Filter only male emp records
print(emps[0].index('m'))
male_recs=list(filter(lambda x:x[3]=='m',emps))
print(male_recs)
print("\n")

#Task3 : Filter those emps whose salaries above 30000 and should belong to dno 12
res2=list(filter(lambda x:x[2]>30000 and x[4]==12,emps))
print(res2)

[50, 60, 70]
[[101, 'ajay', 10000, 'm', 11, 'hyd'], [103, 'priya', 300000, 'f', 13, 'hyd'], [104, 'Anitha', 40000, 'f', 14, 'hyd']]


3
[[101, 'ajay', 10000, 'm', 11, 'hyd'], [102, 'rahul', 20000, 'm', 12, 'pune'], [105, 'jame', 500000, 'm', 15, 'pune']]


[]


In [ ]:
#map() :for each element transformation
#map() also takes 2 arguments
#1.lambda
#2.collection like list

#ex:1
list1=[10,20,30,40,50]
#task :adding 5 each of element of the list
res=list(map(lambda x:x+5,list1)) #here x is each element of list of type int
print(res)

#ex:2
emps=[[101,"ajay",10000,'m',11,'hyd'],
      [102,"rahul",20000,'m',12,'pune'],
      [103,"priya",300000,'f',13,'hyd'],
      [104,"Anitha",40000,'f',14,'hyd'],
      [105,"jame",500000,'m',15,'pune']
     ]
#Task1 : Adding 5000 to the sals of each employee as bonus
res2=list(map(lambda x:[x[0],x[1],x[2]+5000,x[3],x[4],x[5]],emps))
print(res2)

#Task2 : Transform each empname to start with uppercase character
res3=list(map(lambda x:[x[0],x[1].capitalize(),x[2]+5000,x[3],x[4],x[5]],emps))
print(res3)

[15, 25, 35, 45, 55]
[[101, 'ajay', 15000, 'm', 11, 'hyd'], [102, 'rahul', 25000, 'm', 12, 'pune'], [103, 'priya', 305000, 'f', 13, 'hyd'], [104, 'Anitha', 45000, 'f', 14, 'hyd'], [105, 'jame', 505000, 'm', 15, 'pune']]
[[101, 'Ajay', 15000, 'm', 11, 'hyd'], [102, 'Rahul', 25000, 'm', 12, 'pune'], [103, 'Priya', 305000, 'f', 13, 'hyd'], [104, 'Anitha', 45000, 'f', 14, 'hyd'], [105, 'Jame', 505000, 'm', 15, 'pune']]


#Working with files

In [ ]:
#open() :for opening a file
#read() :for reading a file
#write():for writing data to a file
#append():for appending a data to a

#whenever we open a file, we need to say for what purpose you are opening the file
#i.e we need to specify the mode, i.e read,write,append etc
#various modes are
#r ------->for reading(default mode)
#     if file already exist and has data-->it-->it removes data and writes
#     if file doesnt exist-->it creates a new file and writes
#a ------->for appending data to the existing file
#     if file already exist and has data->it-->it appends data at the end
#     if file doesnt exist-->it creates a new file and appends

#w+---> for both writing and reading
#  ---- here the previous data in the file gets removed

#r+ --->for the reading and writing
#------>here the previous data is not removed
#----->here cursor will point to the beginning of the file

#a+ --->for appending and reading
#------>here the previous data is not removed
#----->here the cursor will point to the end of the file
#==============================================================================
#For Reading data from a file--> we have 3 methods
#1.read      :reads the entire file and returns multiline strings
#2.readline():reads a particular line and returns single line string
#3.readlines():reads the entire file and creates list
#       in the file how many lines we have, those many element in the list
#       if files has 10 lines--->then we see 10 element in the list
# Ex:1 Reading a data from a file
#say--->pwd--->present wotking directry---->"/content"
f=open("/content/demo1.txt",mode="r") #f is the file object created for reading only
print(f.read())
f.close()

1. Python is Simple
2. Python is user-friendly
3. Python supports interactive mode
4. Python supports 89300 modules
5. Python has many built-in libraries
6. Python supports object-oriented programming
7. Python supports all major databases
8. Python is dynamic typed
9. Python provides simple syntaxes
10.Python is extensible.


In [ ]:
#tell and seek()
#tell :tells where currently the cursor is
#seek():moving the cursor to the desired position
f=open("/content/demo1.txt",mode="r")
print(f.tell()) #cursor---> at the start of the file
print(f.read())   #cursor---> at the end of the file
print(f.tell()) # "                 "
f.seek(7)
print(f.tell())
print(f.read())
f.seek(0)
print(f.read(9))
f.close()

0
1. Python is Simple
2. Python is user-friendly
3. Python supports interactive mode
4. Python supports 89300 modules
5. Python has many built-in libraries
6. Python supports object-oriented programming
7. Python supports all major databases
8. Python is dynamic typed
9. Python provides simple syntaxes
10.Python is extensible.
335
7
on is Simple
2. Python is user-friendly
3. Python supports interactive mode
4. Python supports 89300 modules
5. Python has many built-in libraries
6. Python supports object-oriented programming
7. Python supports all major databases
8. Python is dynamic typed
9. Python provides simple syntaxes
10.Python is extensible.
1. Python


In [ ]:
#readline():Reads a particular lime ctrl goes to next line
f=open("/content/demo1.txt",mode="r")
print(f.tell())
print(f.readline())
print(f.tell())
print(f.readline())
print(f.tell())
print(f.readline())
print(f.tell())
f.seek(10)
print(f.readline())
f.close()

0
1. Python is Simple

21
2. Python is user-friendly

49
3. Python supports interactive mode

86
is Simple



In [ ]:
#Read or print only the 4th file
f=open("/content/demo1.txt",mode="r")
f.readline()
f.readline()
f.readline()
print(f.readline())

4. Python supports 89300 modules



In [ ]:
#using for loop reading the 4thline
f=open("/content/demo1.txt",mode="r")
for p in range(1,4):
  f.readline()
print(f.readline())
f.close()

4. Python supports 89300 modules



In [ ]:
#particular a particular word/words in a file
f=open("/content/demo1.txt",mode="r")
x=f.read()
#word count-->how many times "python" has occured in this file
print(x.count("Python"))
y=x.replace("Python","Java")
print(y)

10
1. Java is Simple
2. Java is user-friendly
3. Java supports interactive mode
4. Java supports 89300 modules
5. Java has many built-in libraries
6. Java supports object-oriented programming
7. Java supports all major databases
8. Java is dynamic typed
9. Java provides simple syntaxes
10.Java is extensible.


In [ ]:
#readline () :readline all line in a file and creates a list with \n behavior
#             If 10lines in a file then 10 elements in the list
f=open("/content/demo1.txt",mode="r")
x=f.readlines()
print(x,type(x),len(x))

#Reading only the 4th line
print(x[3])

In [ ]:
#write operations:
#python code to create a new file and write data into it
f=open("/content/student.txt",mode="w") #here file object f is created only for writing data
f.write("501,Ajay,CSE,90")
f.write("\n502,Ramesh,ECE,70")
f.write("\n503,Ram,CSE,80")
f.close()

In [ ]:
#python code to create a new file and write data into it
#w+ mode:
f=open("/content/students2.txt",mode="w+") #here file object f is created only for write/Read data
dat='''
501,Ajay,CSE,90
502,Ramesh,ECE,70
503,Ram,CSE,80
'''
f.write(dat)
f.seek(0)
print(f.read())
f.close()


501,Ajay,CSE,90
502,Ramesh,ECE,70
503,Ram,CSE,80



In [ ]:

#r+ mode:
f=open("/content/students2.txt",mode="r+") #here file object f is created only for write/Read data
dat='''
501,Ajay,CSE,90
502,Ramesh,ECE,70
503,Ram,CSE,80
'''
print(f.read())
f.write("504,Rajesh,CSE,60")
f.write("\n505,Amresh,CSE,50")
f.seek(0)
print(f.read())
f.close()

#It reads the existing data(3lines) and to that adding(writing) 2 more lines
#but without


501,Ajay,CSE,90
502,Ramesh,ECE,70
503,Ram,CSE,80

504,Rajesh,CSE,60
505,Amresh,CSE,60
504,Rajesh,CSE,60
505,Amresh,CSE,50
504,Rajesh,CSE,60
505,Amresh,CSE,50
504,Rajesh,CSE,60
505,Amresh,CSE,50

501,Ajay,CSE,90
502,Ramesh,ECE,70
503,Ram,CSE,80

504,Rajesh,CSE,60
505,Amresh,CSE,60
504,Rajesh,CSE,60
505,Amresh,CSE,50
504,Rajesh,CSE,60
505,Amresh,CSE,50
504,Rajesh,CSE,60
505,Amresh,CSE,50504,Rajesh,CSE,60
505,Amresh,CSE,50


In [ ]:
ls

sample_data/  students2.txt  student.txt


In [ ]:
cat /content/students2.txt


501,Ajay,CSE,90
502,Ramesh,ECE,70
503,Ram,CSE,80

504,Rajesh,CSE,60
505,Amresh,CSE,60
504,Rajesh,CSE,60
505,Amresh,CSE,50
504,Rajesh,CSE,60
505,Amresh,CSE,50
504,Rajesh,CSE,60
505,Amresh,CSE,50504,Rajesh,CSE,60
505,Amresh,CSE,50

In [ ]:

#a+ mode: appending and reading
f=open("/content/emps.csv",mode="a+") #It creates a new file and appends data
data='''
101,Ajay,50000,11,Hyd
102,Rahul,60000,12,Pune
103,Ajith,70000,13,chennai
'''
f.write(data) #appending data to the file
f.seek(0)
print(f.read())
f.close()


101,Ajay,50000,11,Hyd
102,Rahul,60000,12,Pune
103,Ajith,70000,13,chennai



In [ ]:
#Reading data from one file and write data to another file
#Read emps.csvfile and write that data into emps.csv by creating it
#i)using readlines
f=open("/content/emps.csv",mode="r")
x=f.readlines() #here x is list
f.close()


f1=open("/content/emps2.csv",mode="w+")
for line in x:
  f1.write(line)
  f1.seek(0)
print(f1.read())
f1.close()

#ii)using read
#read emps.csv data and write that into emps3.csv using read() method
f=open("/content/emps.csv",mode="r")
x=f.read() #here x is multiline string
f.close()

f1=open("/content/emps3.csv",mode="w")
f1.write(x)
f1.seek(0)
f1.close()

103,Ajith,70000,13,chennai



In [ ]:
x=[10,20,30,40,50,60]
#extract first 3 elements
print(x[0:3])
print(x[ :3])

#extract last 3 element
print(x[-3: ])
print(x[ 3:])

[10, 20, 30]
[10, 20, 30]
[40, 50, 60]


In [ ]:
cat /content/students2.txt


501,Ajay,CSE,90
502,Ramesh,ECE,70
503,Ram,CSE,80

504,Rajesh,CSE,60
505,Amresh,CSE,60
504,Rajesh,CSE,60
505,Amresh,CSE,50
504,Rajesh,CSE,60
505,Amresh,CSE,50
504,Rajesh,CSE,60
505,Amresh,CSE,50504,Rajesh,CSE,60
505,Amresh,CSE,50

In [ ]:
#read only the last 2lines from the above file(student)
f=open("/content/students2.txt",mode="r")
x=f.readlines()#here x is a list with 5 elements(lines)
y=x[-2:] #A new list with last 2 element(last2 lines)
print(y)
for p in y: #printing the 2 lines using for loop
  print(p)
f.close()

['505,Amresh,CSE,50504,Rajesh,CSE,60\n', '505,Amresh,CSE,50']
505,Amresh,CSE,50504,Rajesh,CSE,60

505,Amresh,CSE,50


In [ ]:
#read only the first 2lines from the above file(student)
f=open("/content/students2.txt",mode="r")
x=f.readlines()#here x is a list with 5 elements(lines)
y=x[0:2] #A new list with last 2 element(last2 lines)
print(y)
for p in y: #printing the 2 lines using for loop
  print(p)
f.close()

['505,Amresh,CSE,50504,Rajesh,CSE,60\n', '505,Amresh,CSE,50']
505,Amresh,CSE,50504,Rajesh,CSE,60

505,Amresh,CSE,50







# Pandas

In [ ]:
#Pandas: For Data Analysis and Data Manipulations
#here we have 2 categories
#1.series(1-D data) :nothing but a column
#2.DataFrames(2-D Tabular data): Collection of Series(columns)


#creating a series
#creating a series from a list
x=[10,20,30,40,50]
import pandas as pd
s=pd.Series(x)
print(s)
#o/p:
'''
0  10
1  20
2  30
3  40
4  50
'''

#ex:2
#2)Create a Series from a dictionary
import pandas as pd
data={"maths":90,"phy":60,"chem":50}
s = pd.Series(data)   #here maths,phy,chme will be taken as indices
print(s)
'''
Output:
maths    90
phy      60
chem     50 '''

print(s["chem"])  #Accessing the element using index
#output: 50
#creating our own indexes:
s = pd.Series(x,index=['a','b','c','d','e']) #here indexes are a,b,c,d,e
print(s)
'''
output:
a    10
b    20
c    30
d    40
e    50 '''

print(s["b"])
print(s[1])
#output:20


#=============================================================================
#Creating DataFrames

#i) Creating Dataframes from a Dictionary
import pandas as pd
#ex:

dict1={'Inter-I':[90,80,70,40,50],
       'Inter-II':[50,40,55,45,40]}

df=pd.DataFrame(dict1)
print(df)

#o/p:
'''
  Inter-I  Inter-II
0       90        50
1       80        40
2       70        55
3       40        45
4       50        40
'''
#---------------------------------------------------------------------------------
import pandas as pd
data={
      "enames":["Miller","Blake","James","John"],
      "sals":[10000,20000,30000,40000]
      }

#passing this dictionary(data) to pandas DataFrame Constructor , so that a dataframe gets created

df1=pd.DataFrame(data)   #here df1 is a dataframe
print(df1)
print("\n\n")
'''
o/p:
  enames   sals
0  Miller  10000
1   Blake  20000
2   James  30000
3    John  40000 '''
#Note here by default we get index starting with 0, even we can have our own index

#----------------------------------------------------------------------------------------------------

#ex:2 Even we can have index as string type

import pandas as pd
data={
      "Sony":[250,350,200,350,300],
      "LG":[300,180,260,180,150],
      "Lenovo":[300,180,260,200,150]
      }
df2 = pd.DataFrame(data, index=["April","May","June","July","August"])
print(df2)
'''
o/p:
        Sony   LG  Lenovo
April    250  300     300
May      350  180     180
June     200  260     260
July     350  200     200
August   300  150     150 '''
print("\n\n")

#ex:3

#Retrieving particular month data(particular row)
print(df2.loc["April"])
'''
o/p:
Sony      250
LG        300
Lenovo    300
Name: April, dtype: int64 '''
print("\n\n")

#-----------------------------------------------------------------------------
#4) Indexing and slicing

#a)printing a specific column(series)

print(df2["LG"])
'''
o/p:
April     300
May       180
June      260
July      200
August    150
Name: LG, dtype: int64
'''
#here we see no colname

#b)Printing a Dataframe
print(df2[["LG"]])
'''
o/p:
         LG
April   300
May     180
June    260
July    200
August  150 '''

#c)printing multiple columns as Dataframe)

print(df2[["LG","Sony"]])

'''
o/p:
         LG  Sony
April   300   250
May     180   350
June    260   200
July    200   200
August  150   300
'''

#d)Slicing a Dataframe
#  Retrieving specific rows

x=df2[0:3]  #The result(x) is also a dataframe
print(x)
'''
o/p:
      Sony   LG  Lenovo
April   250  300     300
May     350  180     180
June    200  260     260
'''


#e)More data selection operations
#Using loc and iloc, you can select certain rows in a data set.
#loc uses string indices
#iloc uses integers.

x=df2.loc[["April","May"]]
print(x)

'''
O/p:
       Sony   LG  Lenovo
April   250  300     300
May     350  180     180
'''
#f) iloc
x=df2.iloc[3]
print(x)
'''
o/p:
Sony      350
LG        200
Lenovo    200
Name: July, dtype: int64
'''


#g)getting morethan one column

x=df2.iloc[:,:]  #all rows and all columns
print(x)
#o/p:
'''
       Sony   LG  Lenovo
April    250  300     300
May      350  180     180
June     200  260     260
July     350  200     200
August   300  150     150
'''
x=df2.iloc[:,1:3]
print(x)

'''
o/p:
        LG  Lenovo
April   300     300
May     180     180
June    260     260
July    200     200
August  150     150
'''
x=df2.iloc[0:3,1:3]
print(x)

'''
o/p:
       LG  Lenovo
April  300     300
May    180     180
June   260     260
'''
x=df2.iloc[0:3,0:3:2]
print(x)

#o/p:
'''
       Sony  Lenovo
April   250     300
May     350     180
June    200     260
'''
#To eaxtract--->250 from the 1st row
x=df2.iloc[0:1,0:1]
print(x)
#------------------------------------------------------------------------------
#h) sorting data
#   df.sort_values()
#By default sorts in ascending order
x=df2.sort_values('LG')
print(x)
'''
o/p:
        Sony   LG  Lenovo
August   300  150     150
May      350  180     180
July     350  200     200
June     200  260     260
April    250  300     300
'''
x=df2.sort_values('LG',ascending=False)
print(x)
'''
o/p:

       Sony   LG  Lenovo
April    250  300     300
June     200  260     260
July     350  200     200
May      350  180     180
August   300  150     150

'''
#i) Renaming a dataframe column
#   Renaming Sony to Samsung
df2.columns=['Samsung','LG','Lenovo']
print(df2.columns)
'''
o/p:

Index(['Samsung', 'LG', 'Lenovo'], dtype='object')
'''
#j) Dropping a column
x=df2.drop('LG',axis=1)
print(x) #here x is also a dataframe
print("hello")
print(df2)

'''
o/p:
      Samsung  Lenovo
April      250     300
May        350     180
June       200     260
July       350     200
August     300     150
'''
print(df2) #it has 3 columns

#Dropping a row
x=df2.drop('May')
print(x)
'''
o/p:
      Samsung  LG  Lenovo
April      250 300     300
June       200 260     260
July       350 200     200
August     300 150     150
'''
#k)Adding new column

df2["oppo"]=df2.eval('LG+100')
print(df2)

'''
o/p:
      Samsung  LG  Lenovo  oppo
April      250 300     300   400
May        350 180     180   280
June       200 260     260   360
July       350 200     200   300
August     300 150     150   250
'''

#Adding a new column---->Mi
df2["Mi"]=pd.Series([350,170,250,250,200],index=["April","May","June","July","August"])
print(df2)
#output:
'''
      Samsung  LG  Lenovo  oppo   Mi
April      250 300     300   400  350
May        350 180     180   280  170
June       200 260     260   360  250
July       350 200     200   300  250
August     300 150     150   250  200 '''

#converting a df to excel
df2.to_excel("mobiles.xlsx")
df2.to_csv("mobiles.csv")

#l)max()
x=df2.LG.max()
print(x)

'''
o/p:300
'''

#n) Missing values in pandas
#isnull(): will tell if a column misses a value

print(df2.isnull())

'''
o/p:
       Samsung   LG  Lenovo  oppo
April     False False  False False
May       False False  False False
June      False False  False False
July      False False  False False'''

#0)Ranking:
#rank():to rank every column according to its value

print(df2.rank())

'''
o/p:
       Samsung  LG  Lenovo  oppo  Mi
April     2.0  5.0    5.0   5.0  4.0
May       4.5  2.5    2.0   2.5  1.0
June      1.0  4.0    4.0   4.0  3.0
July      4.5  2.5    5.0   4.5  2.0
August    3.0  1.0    1.0   1.0  5.0
'''
#p) Concentrating 2 dataframes
#conccat():we can concatenate two or more frame DataFrames
x=pd.concat([df2,df2])
print(x)

'''o/p:
        Samsung  LG  Lenovo  oppo
April      250  300     300   400
May         350  180     180   280
June        200  260     260   360
July        150  200     200   300
August      300  150     150   250
April       250  300     300   400
May         350  180     180   280
June        200  260     260   360
July        150  200     200   300
August      300  150     150   250 '''



0    10
1    20
2    30
3    40
4    50
dtype: int64
maths    90
phy      60
chem     50
dtype: int64
50
a    10
b    20
c    30
d    40
e    50
dtype: int64
20
20
   Inter-I  Inter-II
0       90        50
1       80        40
2       70        55
3       40        45
4       50        40
   enames   sals
0  Miller  10000
1   Blake  20000
2   James  30000
3    John  40000



        Sony   LG  Lenovo
April    250  300     300
May      350  180     180
June     200  260     260
July     350  180     200
August   300  150     150



Sony      250
LG        300
Lenovo    300
Name: April, dtype: int64



April     300
May       180
June      260
July      180
August    150
Name: LG, dtype: int64
         LG
April   300
May     180
June    260
July    180
August  150
         LG  Sony
April   300   250
May     180   350
June    260   200
July    180   350
August  150   300
       Sony   LG  Lenovo
April   250  300     300
May     350  180     180
June    200  260     260
       Sony   LG  L

/tmp/ipython-input-1739454217.py:48: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])


'o/p:\n        Samsung  LG  Lenovo  oppo\nApril      250  300     300   400\nMay         350  180     180   280\nJune        200  260     260   360\nJuly        150  200     200   300\nAugust      300  150     150   250\nApril       250  300     300   400\nMay         350  180     180   280\nJune        200  260     260   360\nJuly        150  200     200   300\nAugust      300  150     150   250 '

In [ ]:
#-----------------------------------------------------------------------------------------------------
#1)Creating a empty Dataframe
import pandas as pd
df = pd.DataFrame()
print(df)
print("\n")
#------------------------------------------------------------------------------------------------------
#2) Create  a DataFrame from list
import pandas as pd
cities = ["Pune","mumbai","chennai","hyd"]
df = pd.DataFrame(cities)
print(df)
print("\n")
'''
o/p:

0    Pune
1    mumbai
2    chennai
3        hyd '''
#------------------------------------------------------------------------------------------------------
#3) Creating a DataFrame from nestedlists
import pandas as pd
data = [['Miller',10000],['Blake',20000],['James',30000]]
df = pd.DataFrame(data,columns=['NAME','SAL'])
print(df)
print("\n")

#o/p:
'''
     NAME    SAL
0  Miller  10000
1   Blake  20000
2   James  30000 '''

#------------------------------------------------------------------------------------------------------
#3) Creating a DataFrame from a list of Dictionaries

import pandas as pd
#ex:1
data = [{'LG':10},{"LG": 5,'Sony':10, 'Samsung': 20}]
df = pd.DataFrame(data)
print(df)

'''
o/p:
   LG  SONY  SAMSUNG
0  10   NaN      NaN
1   5  10.0     20.0'''

#ex:2
data = [{'LG': 5, 'SONY': 10, 'SAMSUNG': 20},{'LG': 10,'SONY':30}]
df = pd.DataFrame(data)
print(df)

#o/p:
'''
   LG  SONY  SAMSUNG
0   5    10     20.0
1  10    30      NaN
'''
print(df.iloc(0))
#o/p:
'''
LG          5.0
SONY       10.0
SAMSUNG    20.0
'''
#-------------------------------------------------------------------------------------------------
#5) Creating our own indexes(string indexes)
import pandas as pd

data=[{'LG': 10, 'SONY': 20,},{'LG': 5, 'SONY': 10, 'SAMSUNG': 20}]
df = pd.DataFrame(data,index=["First","second"])
print(df)
'''
o/p:
       LG SONY SAMSUNG
first  10   20     NaN
second 5    10     20.0
'''


#-------------------------------------------------------------------------------------------------


Empty DataFrame
Columns: []
Index: []


         0
0     Pune
1   mumbai
2  chennai
3      hyd


     NAME    SAL
0  Miller  10000
1   Blake  20000
2   James  30000


   LG  Sony  Samsung
0  10   NaN      NaN
1   5  10.0     20.0
   LG  SONY  SAMSUNG
0   5    10     20.0
1  10    30      NaN
        LG  SONY  SAMSUNG
First   10    20      NaN
second   5    10     20.0


'\no/p:\n       LG SONY SAMSUNG\nfirst  10   20     NaN\nsecond 5    10     20.0\n'

In [ ]:
#Reading data from a csv file
import pandas as pd

df = pd.read_csv("/content/emp1.csv") #Note: read_excel() for reading from excel file
print(df)
print("\n\n")


#To remove the index
df = pd.read_csv('/content/emp1.csv',index_col=0)
print(df)

print("\n\n")

#For no header
df = pd.read_csv("/content/emp1.csv",header=None)
print(df)
print("\n\n")

   Eid   Ename  Salary  dno  city
0  101  Miller   10000   11   hyd
1  102   Blake   20000   12  pune
2  103    Sony   30000   12   hyd
3  104    Sita   40000   11  pune
4  105    John   50000   13   hyd



      Ename  Salary  dno  city
Eid                           
101  Miller   10000   11   hyd
102   Blake   20000   12  pune
103    Sony   30000   12   hyd
104    Sita   40000   11  pune
105    John   50000   13   hyd



     0       1       2    3     4
0  Eid   Ename  Salary  dno  city
1  101  Miller   10000   11   hyd
2  102   Blake   20000   12  pune
3  103    Sony   30000   12   hyd
4  104    Sita   40000   11  pune
5  105    John   50000   13   hyd





In [ ]:
#Reading a Excel file
import pandas as pd
df = pd.read_excel("/content/emp.xlsx")
print(df)

#again from this df,recreate a excel file(emp2.xlsx)
df.to_excel("emp2.xlsx")

   Eid   Ename  Salary  dno  city
0  101  Miller   10000   11   Hyd
1  102   Blake   20000   12  Pune
2  103    Sony   30000   11   hyd
3  104    Sita   40000   12  pune
4  105    John   50000   13   hyd


In [ ]:
#Creating data from a json file and creating a df
import pandas as pd
df=pd.read_json("/content/cars.json")
print(df)

#From the above df,re-create a json,Excel and csv file (cars1.json,cars2.xlsx,cars3.csv)
df.to_json("cars1.json")
df.to_excel("cars2.xlsx")
df.to_csv("cars3.csv")

     Name    Price  Model  Power
0   swift  1000000   2005   1300
1  Toyota  1200000   2010   1600
2    Audi  2500000   2017   1800
3    Ford  2800000   2009   1200


In [ ]:
#Dataframe filtering operations

#Filtering data from a Dataframe

# importing pandas
import pandas as pd

data = {
  'Name': ['Miller','Blake','James','Jimmy','Sony','Ruby' ],
  'Age': [23,24,22,25,23,22],
  'Gender':['m','m','m','f','f','f'],
  'Branch':['CSE','ECE','EEE','IT','CSE','ECE'],
  'Percentage': [84,82,78,76,68,56],
  }
# Create a dataframe
df=pd.DataFrame(data, columns =['Name','Age','Gender','Branch','Percentage'])
print(df)
print("\n")

#-------------------------------------------------------------------------------------------------------

#i.filtering data based on percentage

df1 = df[df['Percentage'] > 80]
print(df1)
#Note: If we filter a Dataframe then the result is also a Dataframe
print("\n")

#or

df1 = df.loc[df['Percentage'] > 80]
print(df1)

print("\n")
#------------------------------------------------------------------------------------------------------

#ii. I want only the CSE students

df1 = df[df['Branch'] == 'CSE']
print(df1)

print("\n")
#------------------------------------------------------------------------------------------------------
#iii. I want other than CSE students
df1 = df[df['Branch'] != 'CSE']
print(df1)

print("\n")

#Note : we can use == , != , >= ,<= ,> , < for filtering the data

#-----------------------------------------------------------------------------------------------------
#iv : isin() method()

#ex:
#I require only those students who belongs to CSE or IT background

options=['CSE','IT']

df3 = df[df['Branch'].isin(options)]
print(df3)

print("\n")

#or
df4 = df.loc[df['Branch'].isin(options)]
print(df4)

print("\n")
#------------------------------------------------------------------------------------------------------

#V :I want to know those students who are from non-CSE background
options=['CSE','IT']

df5 = df[~df['Branch'].isin(options)]
print(df5)
print("\n")
#------------------------------------------------------------------------------------------------------

#Vi. Providing multiple conditions
#I want those students whose percentage < 70 and are non-CSE Background
df6 = df[(df['Percentage'] < 70) &
        ~df['Branch'].isin(options)]
print(df6)

     Name  Age Gender Branch  Percentage
0  Miller   23      m    CSE          84
1   Blake   24      m    ECE          82
2   James   22      m    EEE          78
3   Jimmy   25      f     IT          76
4    Sony   23      f    CSE          68
5    Ruby   22      f    ECE          56


     Name  Age Gender Branch  Percentage
0  Miller   23      m    CSE          84
1   Blake   24      m    ECE          82


     Name  Age Gender Branch  Percentage
0  Miller   23      m    CSE          84
1   Blake   24      m    ECE          82


     Name  Age Gender Branch  Percentage
0  Miller   23      m    CSE          84
4    Sony   23      f    CSE          68


    Name  Age Gender Branch  Percentage
1  Blake   24      m    ECE          82
2  James   22      m    EEE          78
3  Jimmy   25      f     IT          76
5   Ruby   22      f    ECE          56


     Name  Age Gender Branch  Percentage
0  Miller   23      m    CSE          84
3   Jimmy   25      f     IT          76
4    Sony  

In [ ]:
#Grouping and aggression in pandas
import pandas as pd
df = pd.read_csv('/content/orders.csv') #df is a DataFrame.
#print (df)

#Reading Specific Rows of a particular column--->5 rows
print (df[0:5]['customer'])

#Reading Specific column
'''We use the multi-axes indexing method called loc() for this purpose
We choose to display the customer and order column for all the rows.'''
#print (df.loc[:,['customer','order']])

#Reading Specific Columns and Rows
'''The read_csv function of the pandas library can also be used to read some specific columns and specific rows.
We use the multi-axes indexing method called .loc() for this purpose.
We choose to display the customer and order column for some of the rows.'''
print(df.loc[[1,3,5],['customer','order']])

#Reading Specific Columns for a Range of Rows
print (df.loc[2:6,['customer','order']])

#------------------------------------------------------------------------------

#Various Aggregations--->sum(),mean(),max(),min(),count()

#How many rows the dataset has i.e how many total orders were made--->using count()
#1.No of orders----->using count()
orders=df['order'].count()
print("NO OF ORDERS:",orders)

#2.Total order value(TOV) generated for all the orders ---->sum()
tot_rev=df['revenue'].sum()
print("TOTAL ORDER VALUE:",tot_rev)

#3.Average order value(AOV) generated for all orders ---->mean()
avg_rev=df['revenue'].mean()
print("AVERAGE ORDER VALUE(AOV):",avg_rev)

#4.Max order value  ---->max()
max_rev=df['revenue'].max()
print("MAX ORDER VALUE:",max_rev)

#5.Min order value  ---->min()
min_rev=df['revenue'].min()
print("MIN ORDER VALUE:",min_rev)

# TASK-1. Calculate total number of orders per customer;
orders_cust=df.groupby('customer')['order'].count()
print("Total No of orders per customer:\n",orders_cust)

#TASK-2: Calculate TOV per customer, TOV  - Total revenue;
TOV_cust=df.groupby('customer')['revenue'].sum()
print("TOV per Customer:\n",TOV_cust)

#TASK-3: Calculate AOV per customer, AOV  - average revenue;
AOV_cust=df.groupby('customer')['revenue'].mean()
print("AOV per Customer: \n",AOV_cust)

# Calculate the count of orders based on order_state
cnt=df.groupby('order_state')['order_state'].count()
print("order_state:\n",cnt)

#multi grouping
#df.groupby(['col1', 'col2']).agg({'col3': [min, max, sum]})
#o/p:
'''
citywise,dnowise---->totsal
hyd 11 --->totsal
hyd 12 --->totsal
hyd 13 --->totsal
pune 11 -->totalsal
pune 12 -->totsal
pune 13 -->totsal
'''
df2 = pd.read_csv('emp1.csv')
df3=df2.groupby(['city','dno']).agg({'Salary':[sum]})
print(df3)
#o/p:
'''
city dno
city dno
hyd  11   10000
     12   30000
     13   50000
pune 11   40000
     12   20000
'''
#-------------------------------------------------------------------------------

#Filtering data:
#Selecting rows in pandas DataFrame based on conditions

#I want only those orders whose ordervalue(revenue) >100
df1 = df[df['revenue'] > 100]
print(df1)
print("\n")
#or
df2 = df.loc[df['revenue'] > 100]
print(df2)
print("\n\n\n")

print("\n")

#I want those orders which are not completed
#ex:2
df3 = df.loc[df['order_state']!='completed']
print(df3)

0    34344
1    22822
2    20400
3     1611
4    35924
Name: customer, dtype: int64
   customer       order
1     22822  FR-X-16957
3      1611  GB-A-73965
5     23968  GB-F-55965
   customer       order
2     20400  FR-Z-49644
3      1611  GB-A-73965
4     35924  FR-P-11267
5     23968  GB-F-55965
6     10837  GB-D-88686
NO OF ORDERS: 120000
TOTAL ORDER VALUE: 4896170
AVERAGE ORDER VALUE(AOV): 40.80141666666667
MAX ORDER VALUE: 3488
MIN ORDER VALUE: 0
Total No of orders per customer:
 customer
1         3
2        49
3        22
4        15
5         3
         ..
42334     1
42336     1
42337     1
42338     1
42339     1
Name: order, Length: 34759, dtype: int64
TOV per Customer:
 customer
1         130
2        1218
3         872
4         666
5         166
         ... 
42334      28
42336      39
42337      18
42338      29
42339      23
Name: revenue, Length: 34759, dtype: int64
AOV per Customer: 
 customer
1        43.333333
2        24.857143
3        39.636364
4        44.4000

/tmp/ipython-input-1868288611.py:77: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df3=df2.groupby(['city','dno']).agg({'Salary':[sum]})


In [ ]:
#Converting a Entire a DataFrame to a list
#df.values.tolist()

from pandas import DataFrame

Product = {'Product':['Tablet','iphone','Laptop','Monitor'],
            'Price': [9000,18000,45000,10000]
            }
df = DataFrame(Product, columns= ['Product', 'Price'])
print(df)
x = df.values.tolist()
print(x,type(x))
print("\n\n")
#------------------------------------------------------------------------------
#ex:2
#If you want to add the column names also into your list
#[df.column.values.tolist()]

from pandas import DataFrame

product = {'Product': ['Tablet','iphone','Laptop','Monitor'],
            'price': [250,800,1200,300]
           }
df = DataFrame(product, columns =['Product','Price'])
#printing the column names of DF within a list
print([df.columns.values.tolist()])
#adding column names list to other list
p_list = [df.columns.values.tolist()]+ df.values.tolist()
print(p_list)

print("\n\n")
#-------------------------------------------------------------------------------
#ex:3
#converting a particular  column of a DataFrame to a list
#df['column name'].values.tolist()

from pandas import DataFrame

product = {'Product': ['Tablet','iphone','Laptop','Monitor'],
            'price': [250,800,1200,300]
           }
df = DataFrame(product,columns= ['Product','Price'])

prod = df['Product'].values.tolist()
print(prod)
print("\n\n")
#----------------------------------------------------------------------------------------------------
#ex:4 appending an additional element into the list
#prod.append('Printer')
from pandas import DataFrame

Product = {'Product': ['Tablet','iphone','Laptop','Monitor'],
            'Price': [250,800,1200,300]
           }
df = DataFrame(Product, columns=['Product', 'Price'])

prod = df['Product'].values.tolist()
prod.append('Printer')

print(prod)

#---------------------------------------------------------------------------------------------------

   Product  Price
0   Tablet   9000
1   iphone  18000
2   Laptop  45000
3  Monitor  10000
[['Tablet', 9000], ['iphone', 18000], ['Laptop', 45000], ['Monitor', 10000]] <class 'list'>



[['Product', 'Price']]
[['Product', 'Price'], ['Tablet', nan], ['iphone', nan], ['Laptop', nan], ['Monitor', nan]]



['Tablet', 'iphone', 'Laptop', 'Monitor']



['Tablet', 'iphone', 'Laptop', 'Monitor', 'Printer']


# Numpy


In [ ]:
#Numpy---->stands for Numerical Python
#Numpy is to perform mathematical and statistical operations.
#It has been built to work with the N-dimensional array, linear algebra,
#random number etc.

import numpy as np

#!pip install numpy

#to know the numpy Version

print(np.__version__)

#ex1: Creating a Numpy Array from a list

list1=[1,2,3,4,5]
print(list1)

array1=np.array(list1)
print(array1,type(array1))

#or
x=np.array ([10,20,30,40,50])

print(x)

print("\n")
#ex:2 performing mathematical operations like additions,subtraction,division and multiplication on an array
y=array1+10
print(y)

z=y-1
print(z)
w=z*2
print(w)

#3) shape of the array and dtype
print(array1.shape)
print(array1.dtype)

#4)float type
array2=np.array([1.5,2.5,3.5,4.5])
print(array2.shape)
print(array2.dtype)

#5)2 dimensional array
c = np.array([[1,2,3],
               [4,5,6]])
print(c)
print(c.shape)   #2-rows and 3 cols
print(c.dtype)

#6) 3 dimensional array
d =np.array([
[[1, 2,3],
 [4, 5, 6]],
[[7, 8,9],
[10, 11, 12]]
])
print(d)
print(d.shape) #(2,2,3) i.e 2 2x3 arrays

#7)np.zeros
# np.ones
#we can create a matrix full of zeroes or ones using np.zeros and np.one commands.
#It can be used when you initialized the weight during the first interations in
#Tensorflow and other statistics tasks.
# syntax :np.zeros(shape, dtype=float)
print(np.zeros((2,3)))

print(np.zeros((2,2), dtype=np.int16))

print(np.ones((1,2,3), dtype=np.int16))  #one 2-D array

2.0.2
[1, 2, 3, 4, 5]
[1 2 3 4 5] <class 'numpy.ndarray'>
[10 20 30 40 50]


[11 12 13 14 15]
[10 11 12 13 14]
[20 22 24 26 28]
(5,)
int64
(4,)
float64
[[1 2 3]
 [4 5 6]]
(2, 3)
int64
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]]
[[[1 1 1]
  [1 1 1]]]
