<a href="https://colab.research.google.com/github/nishant26baisoya-code/Data-science_gen_-ai_project/blob/main/Standard_Scaler_standardization_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import the required Libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [ ]:
#Loading the dataset
df=pd.read_csv("loan_eligibility_dataset.csv")

#Display first few rows to understand the dataset
print(df.head())

   CustomerID  Income  LoanAmount  CreditScore  DebtToIncomeRatio LoanApproved
0           1   45795       46606          771               0.27           No
1           2   30860       92313          362               0.65           No
2           3  133694      146699          438               0.00          Yes
3           4  149879       13792          798               0.35           No
4           5  140268      179073          691               0.30          Yes


In [ ]:
#Selecting numerical column for scaling
numerical_features=["Income","LoanAmount","CreditScore","DebtToIncomeRatio"]

#Crearting a dataframe for numerical features
df_numerical=df[numerical_features]




In [ ]:
#Initilaize Standardscaler
standard_scaler=StandardScaler()

#Apply standard scaler Transformation
df_standard_scaling=standard_scaler.fit_transform(df_numerical)
print(df_standard_scaling)

#Converting to a Dataframe
df_standard_scaled=pd.DataFrame(df_standard_scaling,columns=numerical_features)

#Display the scaled data
print("\n Standard Scaled Data(Z-score normalization):\n",df_standard_scaled.head())

[[-1.27166466e+00 -7.44735781e-01  1.11369350e+00 -7.29005720e-01]
 [-1.69869443e+00  2.62580175e-02 -1.25156064e+00  7.09323322e-01]
 [ 1.24159215e+00  9.43650730e-01 -8.12051311e-01 -1.75097636e+00]
 [ 1.70436262e+00 -1.29824816e+00  1.26983497e+00 -4.26199606e-01]
 [ 1.42955960e+00  1.48974111e+00  6.51052105e-01 -6.15453427e-01]
 [ 4.73195886e-01  1.16749145e+00  8.07193576e-01 -1.14536413e+00]
 [-1.53953170e-01 -2.97020608e-01  5.54013072e-02  2.55114151e-01]
 [-1.54415169e+00  6.49199820e-01  5.75872878e-01  6.58603298e-02]
 [ 6.32342035e-01  5.80563205e-01  1.21778782e+00  8.60726380e-01]
 [-6.59812617e-01  1.16050802e+00 -2.80013705e-01 -7.29005720e-01]
 [ 7.78507166e-01  6.51139660e-01 -1.37878702e+00 -8.42558013e-01]
 [ 1.49986868e+00 -6.27518814e-01 -1.45396625e+00 -1.10751336e+00]
 [-4.61466077e-01 -1.15711212e+00 -8.35183381e-01 -9.18259541e-01]
 [-2.11013041e-04  4.17549136e-01 -4.53504229e-01  3.68666444e-01]
 [-1.26514555e+00  3.50413788e-01 -1.42505116e+00 -2.36945784e

In [ ]:
#MinMaxScaler Method

In [ ]:
#initialize MinMaxScaler
min_max_scaler=MinMaxScaler()

#Apply MinMaxScaler Transformation(on the i/p features dataframe)
minmax_scaling=min_max_scaler.fit_transform(df_numerical)

#converting/creating a DataFrame
df_minmax_scaled=pd.DataFrame(minmax_scaling,columns=numerical_features)

#Display the scaled data
print("\n Min-Max Scaled Data (Range 0-1):\n",df_minmax_scaled.head())


 Min-Max Scaled Data (Range 0-1):
      Income  LoanAmount  CreditScore  DebtToIncomeRatio
0  0.126152    0.209486     0.861624               0.27
1  0.000764    0.445381     0.107011               0.65
2  0.864117    0.726068     0.247232               0.00
3  1.000000    0.040132     0.911439               0.35
4  0.919310    0.893151     0.714022               0.30


In [ ]:
#Save standard scaled Dataset
df_standard_scaled.to_csv("standard_scaled_loan_data.csv",index=False)
#Save Min-Max Scaled DataSet
df_minmax_scaled.to_csv("minmax_scaled_loan_data.csv",index=False)
